tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eff0f6",
        "surface-container-high": "#e7e8ee",
        "primary-fixed-dim": "#a1c9ff",
        "on-primary-fixed-variant": "#004880",
        "on-tertiary-fixed-variant": "#733500",
        "secondary-fixed-dim": "#7dd0ff",
        "secondary-fixed": "#c4e7ff",
        "tertiary-fixed-dim": "#ffb688",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "primary-fixed": "#d2e4ff",
        "on-tertiary-container": "#ffb98d",
        "on-tertiary-fixed": "#311300",
        "on-secondary-fixed-variant": "#004c69",
        primary: "#003e6f",
        "error-container": "#ffdad6",
        tertiary: "#642d00",
        "primary-container": "#005696",
        "surface-tint": "#1961a1",
        secondary: "#00658b",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbc7",
        "on-background": "#191c20",
        "on-secondary-container": "#005575",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e2e8",
        "on-surface-variant": "#414750",
        background: "#f8f9ff",
        "outline-variant": "#c1c7d2",
        outline: "#727781",
        "on-surface": "#191c20",
        "on-secondary-fixed": "#001e2c",
        "inverse-primary": "#a1c9ff",
        "surface-container": "#ededf4",
        "surface-dim": "#d9dae0",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        surface: "#f8f9ff",
        "tertiary-container": "#874001",
        "secondary-container": "#6ecbfe",
        "on-primary": "#ffffff",
        "on-primary-container": "#a5cbff",
        "surface-variant": "#e1e2e8",
        "surface-container-low": "#f2f3f9",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2e3035",
        "on-primary-fixed": "#001c37",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
